### ISSUE TITLE
I've already done this lab. 

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/array-readme#19]
I remember completing this lab when it was titled _intro-to-simple-array-manipulations-001-prework-web_
so naturally I'm curious when I see what were once complete sections incomplete with new labs testing the same knowledge.

This seems to occur frequently because I was the guy who was half way through the old Flatiron Prework when Learn.co was launched invalidating my progress, at least this time I only have to go back in and remaster old content.

**Comment by AnnJohn** [comment]
Yes, the pre-work contains some of the labs in the Lea
