### ISSUE TITLE
Feedback on Array Readme

### ISSUE THREAD

**Issue by sev2109** [learn-co-curriculum/array-readme#20]
This readme and video cover how to remove items from the beginning and end of an array, but it doesn't say how to remove from the middle. I guess that can be looked up in the Ruby documentation, but it could be nice to have it in the Readme too!

Thanks :)

SV

**Comment by AnnJohn** [comment]
Thanks for the feedback @sev2109! Yup, we would like people to use the Ruby documentation. We'll add a note in the readme.
