### ISSUE TITLE
Lab not marked complete bug?

### ISSUE THREAD

**Issue by bjacooper** [learn-co-curriculum/array-readme#25]
Hi there, 

I'm about 99.9% sure I've done this lab already in the intro track, but it's not marked as completed. I got this same feeling on a couple of other labs too. Wondering if this is intended or is a bug?

**Comment by AnnJohn** [comment]
hi @bjacooper this readme is slightly different than the one in the qualifying track (you'll see the that the github urls for both lessons are different). feel free to mark this one as complete and then move on from there. thanks.
