### ISSUE TITLE
Class Constructor too early?

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/array-readme#3]
explaining Array.new may not be worthwhile before dicussing classes, initializers, and inheritance. IMO it's enough to say they can create an empty array with `[]`.

**Comment by SophieDeBenedetto** [comment]
so talked about this briefly w/ joe in the past--we want to give them a full intro but tell them not to worry too much about classes right now. So the note below is meant to achieve that. I think good to briefly mention to get them thinking about the wider world of OOP then less of a weird/tough shift when we really get into it. Gonna close this but come find me if you want to talk more about it

**Comment by wifelette** [comment]
I know this is closed, but I'll add a vote in the direction of the original issue :p 

I found the way it's just shown but not at all explained pretty jarring. It seemed in theory pretty useful/important... but then you wouldn't show me how it worked :p 

Even if you don't want to go into the concept in full detail here, this precise level of info doesn't accomplish much beyond being frustrating ("Here's this cool thing that sounds theoretically important, but we won't explain how it works in practice _at all_, so here's some code you don't know how to read just to frustrate you. PSYCH!"). 

Recommend either pulling it out altogether, or explaining in at least a little more detail. It's still totally fine to have us not work with it until a future lesson, that's happened before in the curriculum, or even to just link to an outside reference page for if a student _does_ want to jump the gun a bit.

**Comment by SophieDeBenedetto** [comment]
Hi @wifelette, thanks for your input. I added a bit of exposition around the `Array.new` syntax. The main point of giving you guys a glimpse of this right now is just to expose you to whats out there and what's coming down the pipeline in this course. 

It should be pretty clear now that `Array.new` is simply another way of making a new, empty array, and that the concepts of objects and classes are a much bigger topic to be discussed later.
